server {
	listen 443 ssl;

	root /var/www/ezeppa.42.fr/html;
	index index.php index.html;

	server_name ezeppa.42.fr;
	
	ssl_certificate     /etc/nginx/ssl/ezeppa.42.fr.crt;
	ssl_certificate_key /etc/nginx/ssl/ezeppa.42.fr.key;
	ssl_protocols       TLSv1.2 TLSv1.3;

	error_log  /var/log/nginx/error.log error;

	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}

	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_pass wordpress_php:9000;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include fastcgi_params;
	}
}